### ISSUE TITLE
Debian package must depend on python3-otp

### ISSUE THREAD

**Issue by glogiotatidis** [bil-elmoussaoui/Gnome-Authenticator#36]
**Reporter info**

 ```
 * Distribution - Debian 9
 ```

**Actual issue**

 - I followed the instructions, added repo and apt-get installed the package
 - python3-pyotp was not installed and app couldn't generate passwords. Manually running `apt-get install python3-pyotp` fixed the issue.

and btw: thanks for building this! :)

**Comment by bil-elmoussaoui** [comment]
I'm not the maintainer of the PPA. So I can't do anything about this :/ Please contact the PPA's maintainer
