### ISSUE TITLE
Default app icon

### ISSUE THREAD

**Issue by emersion** [bil-elmoussaoui/Gnome-Authenticator#9]
The default icon is ugly :P

**Comment by bil-elmoussaoui** [comment]
There's no default icon :( and i'm the worst designer on this planet

**Comment by emersion** [comment]
You could always use something like `categories/applications-internet`

**Comment by bil-elmoussaoui** [comment]
Yeah i know, but i've always hated the applications that used an icon that they shouldn't do :P I prefer to wait until someone design a proper icon...

**Comment by alpha** [comment]
A fix is on the way ;)
![512x512](https://cloud.githubusercontent.com/assets/4603691/15984491/e6defe62-2fd5-11e6-893f-b18024ab2a10.png)

**Comment by bil-elmoussaoui** [comment]
Done thanks to @alphaphee 💯
